/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessStoriesIndexRouteImport } from './routes/success-stories.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SuccessStoriesSlugRouteImport } from './routes/success-stories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesIndexRoute = SuccessStoriesIndexRouteImport.update({
  id: '/success-stories/',
  path: '/success-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesSlugRoute = SuccessStoriesSlugRouteImport.update({
  id: '/success-stories/$slug',
  path: '/success-stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/success-stories': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/solutions'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/solutions'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/solutions'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  SolutionsRoute: typeof SolutionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SuccessStoriesSlugRoute: typeof SuccessStoriesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SuccessStoriesIndexRoute: typeof SuccessStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/': {
      id: '/success-stories/'
      path: '/success-stories'
      fullPath: '/success-stories/'
      preLoaderRoute: typeof SuccessStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/$slug': {
      id: '/success-stories/$slug'
      path: '/success-stories/$slug'
      fullPath: '/success-stories/$slug'
      preLoaderRoute: typeof SuccessStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  SolutionsRoute: SolutionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  SuccessStoriesSlugRoute: SuccessStoriesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  SuccessStoriesIndexRoute: SuccessStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
